name: "test jfs on windows"

on:
  push:
    branches: [ main ]
  pull_request:
    #The branches below must be a subset of the branches above
    branches: [ main ]



jobs:
  wintest:
    runs-on: windows-2022
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Include Headers
        run: |
          mkdir "C:\WinFsp\inc\fuse"
          copy .\hack\winfsp_headers\ "C:\WinFsp\inc\fuse"
          dir "C:\WinFsp\inc\fuse"
          set CGO_CFLAGS=-I/C/WinFsp/inc/fuse
          go env


      - name: Build Juicefs
        run: |
          go build -ldflags="-s -w" -o juicefs.exe ./cmd



