name: "test jfs on windows"

on:
  push:
    branches: [ main ]
  pull_request:
    #The branches below must be a subset of the branches above
    branches: [ main ]



jobs:
  wintest:
    runs-on: windows-2022
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Scoop
        run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          iwr -useb get.scoop.sh | iex
          echo $env:USERNAME
          scoop

      - name: Install Redis
        run: |
          scoop install redis
          redis-server --service-install --loglevel verbose
          redis-server --service-start

      - name: Install MinIO
        run: |
          scoop install minio
          scoop install curl
          curl  https://repo.jenkins-ci.org/releases/com/sun/winsw/winsw/2.9.0/winsw-2.9.0-net4.exe -o minio-service.exe
          mkdir "C:\tmp"
          echo  "<service>"   >> minio-service.xml
          echo  "<id>MinIO</id>"  >> minio-service.xml
          echo  "<name>MinIO</name>"  >> minio-service.xml
          echo  "<description>MinIO</description>"  >> minio-service.xml
          echo  "<executable>C:\Users\$env:USERNAME\scoop\shims\minio.exe</executable>"  >> minio-service.xml
          echo  "<arguments>server C:\tmp</arguments>"  >> minio-service.xml
          echo  "<logmode>rotate</logmode>"  >> minio-service.xml
          echo  "</service>"  >> minio-service.xml
          .\minio-service.exe install
          net start MinIO


      - name: Install WinFsp
        run: |
          choco install winfsp -y

      - name: Set up Include Headers
        run: |
          mkdir "C:\WinFsp\inc\fuse"
          copy .\hack\winfsp_headers\* C:\WinFsp\inc\fuse\
          dir "C:\WinFsp\inc\fuse"
          set CGO_CFLAGS=-IC:/WinFsp/inc/fuse
          go env
          go env -w CGO_CFLAGS=-IC:/WinFsp/inc/fuse
          go env

      - name: Build Juicefs
        run: |
          go env
          go build -ldflags="-s -w" -o juicefs.exe ./cmd

      - name: Juicefs Format
        run: |
          ./juicefs.exe format \
              --storage minio \
              --bucket http://127.0.0.1:9000/pics \
              --access-key minioadmin \
              --secret-key minioadmin \
              redis://127.0.0.1:6379/1 \
              pics

      - name: Juicefs Mount
        run: |
          ./juicefs.exe mount redis://127.0.0.1:6379/1 Z:
