name: "test jfs on windows"

on:
  push:
    branches: [ main ]
  pull_request:
    #The branches below must be a subset of the branches above
    branches: [ main ]



jobs:
  wintest:
    runs-on: windows-2022
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Docker Desktop
        run: |
          choco install docker-desktop -y

      - name: Test Containers
        run: |
          docker version
          "C:\Program Files\Docker\Docker\Docker Desktop.exe"
          docker version
          "C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchDaemon

      - name: Start Redis
        run: |
          docker run -d --name redis -p 6379:6379  redis redis-server --appendonly yes

      - name: Start Minio
        run: |
          docker run -d --name minio -p 9000:9000  -p 9900:9900 minio/minio server /data 

      - name: Install WinFsp
        run: |
          choco install winfsp -y

      - name: Set up Include Headers
        run: |
          mkdir "C:\WinFsp\inc\fuse"
          copy .\hack\winfsp_headers\* C:\WinFsp\inc\fuse\
          dir "C:\WinFsp\inc\fuse"
          set CGO_CFLAGS=-IC:/WinFsp/inc/fuse
          go env
          go env -w CGO_CFLAGS=-IC:/WinFsp/inc/fuse
          go env

      - name: Build Juicefs
        run: |
          go env
          go build -ldflags="-s -w" -o juicefs.exe ./cmd

      - name: Juicefs Format
        run: |
          ./juicefs.exe format \
              --storage minio \
              --bucket http://127.0.0.1:9000/pics \
              --access-key minioadmin \
              --secret-key minioadmin \
              redis://127.0.0.1:6379/1 \
              pics

      - name: Juicefs Mount
        run: |
          ./juicefs.exe mount redis://127.0.0.1:6379/1 Z:
